# grpc:
#   client:
#     authService:
#       address: :"static://localhost:9092"
#       negotiationType: PLAINTEXT
#     productService:
#       address: "static://localhost:9090"
#       negotiationType: PLAINTEXT

