# grpc:
#   client:
#     authService:
#       address: :"static://localhost:9092"
#       negotiationType: PLAINTEXT
#     productService:
#       address: "static://localhost:9090"
#       negotiationType: PLAINTEXT

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
